EMS/Controllers/DepartmentController.cs
using BussinessLayer.Interface;
using EMS.Common;
using Microsoft.AspNetCore.Mvc;
using Model;

namespace EMS.Controllers
{
    public class DepartmentController : Controller
    {
        private IDepartmentManager _departmentManager;
        public DepartmentController(IDepartmentManager departmentManager)
        {
            _departmentManager = departmentManager;
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(DepartmentModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    string message = _departmentManager.AddDepartment(model);
                    if (message == AppConstant.alreadyExists)
                    {
                        ViewBag.Message = message;
                        return View();
                    }
                    return RedirectToAction("Create", "Employee");
                }
                return View();
            }
            catch (System.Exception)
            {
                return View("Error");
                throw;
            }
           
        }
    }
}

EMS/Controllers/DesignationController.cs
using BussinessLayer.Interface;
using EMS.Common;
using Microsoft.AspNetCore.Mvc;
using Model;

namespace EMS.Controllers
{
    public class DesignationController : Controller
    {
        private IDesignationManager _designationManager;
        public DesignationController(IDesignationManager designationManager)
        {
            _designationManager = designationManager;
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(DesignationModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var message = _designationManager.AddDesignation(model);
                    if (message == AppConstant.alreadyExists)
                    {
                        ViewBag.Message = message;
                        return View();
                    }
                    return RedirectToAction("Create", "Employee");
                }
                return View();
            }
            catch (System.Exception)
            {
                return View("Error");
                throw;
            }
            
        }
    }
}

EMS/Controllers/EmployeeController.cs
using BussinessLayer.Interface;
using EMS.Common;
using Microsoft.AspNetCore.Mvc;
using Model;
using System.Collections.Generic;
using System.Linq;
using static CommonLayer.Utility;

namespace EMS.Controllers
{
    public class EmployeeController : Controller
    {
        private IEmployeeManager _employeeManager;
        private IDepartmentManager _departmentManager;
        private IDesignationManager _designationManager;
        public EmployeeController(IEmployeeManager employeeManager, IDepartmentManager departmentManager, IDesignationManager designationManager)
        {
            _employeeManager = employeeManager;
            _departmentManager = departmentManager;
            _designationManager = designationManager;
        }

        public IActionResult Index(string sortField, string currentSortField, string currentSortOrder, string currentFilter, string SearchByEmpTag, string SearchByFirstName, string SearchByEmail, int? pageNo)
        {
            try
            {
                if (SearchByEmpTag != null)
                {
                    pageNo = 1;
                }
                else
                {
                    SearchByEmpTag = currentFilter;
                }

                var deleteMessage = TempData["DeleteMessage"] as string;
                ViewBag.DeleteMessage = deleteMessage;

                var Addedmessage = TempData["SucessFullyAddedMessage"] as string;
                ViewBag.SucessFullyAddedMessage = Addedmessage;

                ViewData["CurrentSort"] = sortField;
                ViewBag.CurrentFilter = SearchByEmpTag;

                var employees = _employeeManager.GetAllEmployees(SearchByEmpTag, SearchByFirstName, SearchByEmail);
                employees = SortEmployeeData(employees, sortField, currentSortField, currentSortOrder);

                return View(PagingList<EmployeeModel>.CreateAsync(employees.AsQueryable<EmployeeModel>(), pageNo ?? 1, 10));
            }
            catch (System.Exception)
            {
                return View("Error");
                throw;
            }
            
        }

        public IActionResult Create()
        {
            ViewBag.Departments = _departmentManager.GetDepartmentDropdownList();
            ViewBag.Designations = _designationManager.GetDesignationDropdownList();
            return View();
        }

        [HttpPost]
        public IActionResult Create(EmployeeModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var message = _employeeManager.AddEmployee(model);
                    if (message == AppConstant.alreadyExists)
                    {
                        ViewBag.Message = message;
                        return View();
                    }
                    TempData["SucessFullyAddedMessage"] = message;
                    return RedirectToAction("Index");
                }
                ViewBag.Departments = _departmentManager.GetDepartmentDropdownList();
                ViewBag.Designations = _designationManager.GetDesignationDropdownList();
                return View();
            }
            catch (System.Exception)
            {
                return View("Error");
                throw;
            }
           
        }
        public IActionResult Edit(int id)
        {
            try
            {
                EmployeeModel data = _employeeManager.GetEmployeeById(id);
                ViewBag.Departments = _departmentManager.GetDepartmentDropdownList();
                ViewBag.Designations = _designationManager.GetDesignationDropdownList();
                return View("Create", data);
            }
            catch (System.Exception)
            {
                return View("Error");
                throw;
            }
          
        }

        [HttpPost]
        public IActionResult Edit(EmployeeModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _employeeManager.UpdateEmployee(model);
                    return RedirectToAction("Index");
                }
                ViewBag.Departments = _departmentManager.GetDepartmentDropdownList();
                ViewBag.Designations = _designationManager.GetDesignationDropdownList();
                return View("Create", model);
            }
            catch (System.Exception)
            {
                return View("Error");
                throw;
            }
           
        }

        public IActionResult Delete(int id)
        {
            try
            {
                var message = _employeeManager.DeleteEmployee(id);
                TempData["DeleteMessage"] = message;
                return RedirectToAction("Index");
            }
            catch (System.Exception)
            {
                return View("Error");
                throw;
            }
           
        }

        private IEnumerable<EmployeeModel> SortEmployeeData(IEnumerable<EmployeeModel> employees, string sortField, string currentSortField, string currentSortOrder)
        {
            try
            {
                if (string.IsNullOrEmpty(sortField))
                {
                    ViewBag.SortField = "EmpTagNumber";
                    ViewBag.SortOrder = "Asc";
                }
                else
                {
                    if (currentSortField == sortField)
                    {
                        ViewBag.SortOrder = currentSortOrder == "Asc" ? "Desc" : "Asc";
                    }
                    else
                    {
                        ViewBag.SortOrder = "Asc";
                    }
                    ViewBag.SortField = sortField;
                }

                var propertyInfo = typeof(EmployeeModel).GetProperty(ViewBag.SortField);
                if (ViewBag.SortOrder == "Asc")
                {
                    employees = employees.OrderBy(s => propertyInfo.GetValue(s, null)).ToList();
                }
                else
                {
                    employees = employees.OrderByDescending(s => propertyInfo.GetValue(s, null)).ToList();
                }
                return employees;
            }
            catch (System.Exception)
            {
                throw;
            }
           
        }
    }
}

EMS/Views/Employee/Create.cshtml
@model Model.EmployeeModel

@{
    ViewData["Title"] = Model != null ? "Edit" : "Create";
}

<div id="message">
    @if (ViewBag.Message != null)
    {
        <p class="alert alert-success">@ViewBag.Message</p>
    }
</div>

<hr />
<div class="card">
    <div class="card-body">
        <h2 class="card-title">@ViewData["Title"] Employee</h2>
        <form asp-action=@ViewData["Title"]>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @if (ViewData["Title"] != null && ViewData["Title"].ToString() == "Edit")
            {
                <input asp-for="Emp_Id" class="form-control" hidden />
            }
            <div class="row m-2">
                <div class="col">
                    <label asp-for="EmpTagNumber" class="control-label required"></label>
                    <input asp-for="EmpTagNumber" class="form-control" maxlength="20"/>
                    <span asp-validation-for="EmpTagNumber" class="text-danger"></span>
                </div>
                <div class="col">
                    <label asp-for="EmailAddress" class="control-label required"></label>
                    <input asp-for="EmailAddress" class="form-control" maxlength="100"/>
                    <span asp-validation-for="EmailAddress" class="text-danger"></span>
                </div>
            </div>
            <div class="row m-2">
                <div class="col">
                    <label asp-for="FirstName" class="control-label required"></label>
                    <input asp-for="FirstName" class="form-control" maxlength="50"/>
                    <span asp-validation-for="FirstName" class="text-danger"></span>
                </div>
                <div class="col">
                    <label asp-for="LastName" class="control-label required"></label>
                    <input asp-for="LastName" class="form-control" maxlength="50"/>
                    <span asp-validation-for="LastName" class="text-danger"></span>
                </div>
            </div>
            <div class="row m-2">
                <div class="col">
                    <label asp-for="Birthdate" class="control-label required"></label>
                    <input asp-for="Birthdate" class="form-control" />
                    <span asp-validation-for="Birthdate" class="text-danger"></span>
                </div>
                <div class="col">

                </div>
            </div>
            <div class="row m-2">
                <div class="col">
                    <label asp-for="DepartmentId" class="control-label required"></label>
                    <select asp-for="DepartmentId" asp-items="@(new SelectList(ViewBag.Departments,"DepartmentId","DepartmentName"))" class="form-control">
                        <option value="">--Select--</option>
                    </select>
                    <span asp-validation-for="DepartmentId" class="text-danger"></span>
                    @*@if (ViewBag.Departments.Count == 0)
                        {
                        }*@
                </div>
                <div class="col">
                    <label asp-for="DesignationId" class="control-label required"></label>
                    <select asp-for="DesignationId" asp-items="@(new SelectList(ViewBag.Designations,"DesignationId","DesignationName"))" class="form-control">
                        <option value="">--Select--</option>
                    </select>
                    <span asp-validation-for="DesignationId" class="text-danger"></span>
                    @*@if (ViewBag.Designations.Count == 0)
                        {
                        }*@
                </div>
            </div>
            <div class="row mt-2 ml-2">
                <div class="col">
                    <a asp-controller="Department" asp-action="Create" class="btn btn-outline-primary mt-2">Add Department</a>
                </div>
                <div class="col">
                    <a asp-controller="Designation" asp-action="Create" class="btn btn-outline-primary mt-2">Add Designation</a>
                </div>
            </div>
            <div class="row mt-3 ml-2">
                <div class="col">
                    <input type="submit" value="Save" class="btn btn-primary" />
                    <a asp-action="Index" class="btn btn-secondary">Cancel</a>
                </div>
                <div class="col">
                </div>
            </div>
        </form>

    </div>
</div>

<script>
    $(document).ready(function () {
        setTimeout(function () {
            $("#message").fadeOut("slow");
        }, 3000);
    });
</script>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
} 

EMS/Views/Employee/Index.cshtml
@*@model IEnumerable<Model.EmployeeModel>*@
@model CommonLayer.Utility.PagingList<Model.EmployeeModel>

<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewData["Title"] = "Employee List";
}

<p>

</p>


<div id="message">
    @if (ViewBag.DeleteMessage != null)
    {
        <div class="alert alert-success">@ViewBag.DeleteMessage</div>
    }
    @if (ViewBag.SucessFullyAddedMessage != null)
    {
        <div class="alert alert-success">@ViewBag.SucessFullyAddedMessage</div>
    }
</div>

@using (Html.BeginForm())
{
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-4">
                    <label class="control-label">Emp Tag :</label>
                    @Html.TextBox("SearchByEmpTag", null, new { @class = "form-control" })
                </div>
                <div class="col-4">
                    <label class="control-label">First Name :</label>
                    @Html.TextBox("SearchByFirstName", null, new { @class = "form-control" })
                </div>
                <div class="col-4">
                    <label class="control-label">Email:</label>
                    @Html.TextBox("SearchByEmail", null, new { @class = "form-control" })
                </div>
            </div>
            <div class="row mt-2">
                <div class="col-6">
                    <input type="submit" value="Search" class="btn btn-primary"/>
                    <input type="button" value="Clear" id="ClearSearch" class="btn btn-danger" onclick="clearFields()" />
                </div>
                <div class="col-6">
                    <a asp-action="Create" class="btn btn-secondary" style="float:right">Add Employee</a>
                </div>
            </div>
        </div>
    </div>
}
<div class="card mt-2">
    <div class="card-body">
        <h2 class="card-title">Employee List</h2>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>
                        @*@Html.DisplayNameFor(model => model.EmpTagNumber)*@
                        @Html.ActionLink("Emp Tag #", "Index", new { sortField = "EmpTagNumber", currentSortField = ViewBag.SortField, currentSortOrder = ViewBag.SortOrder, currentFilter = ViewBag.CurrentFilter })
                    </th>
                    <th>
                        @Html.ActionLink("EmailAddress", "Index", new { sortField = "EmailAddress", currentSortField = ViewBag.SortField, currentSortOrder = ViewBag.SortOrder, currentFilter = ViewBag.CurrentFilter })
                    </th>
                    <th>
                        @Html.ActionLink("First Name", "Index", new { sortField = "FirstName", currentSortField = ViewBag.SortField, currentSortOrder = ViewBag.SortOrder, currentFilter = ViewBag.CurrentFilter })
                    </th>
                    <th>
                        @Html.ActionLink("Last Name", "Index", new { sortField = "LastName", currentSortField = ViewBag.SortField, currentSortOrder = ViewBag.SortOrder, currentFilter = ViewBag.CurrentFilter })
                    </th>
                    <th>
                        @Html.ActionLink("Department", "Index", new { sortField = "DepartmentName", currentSortField = ViewBag.SortField, currentSortOrder = ViewBag.SortOrder, currentFilter = ViewBag.CurrentFilter })
                    </th>
                    <th>
                        @Html.ActionLink("Designation", "Index", new { sortField = "DesignationName", currentSortField = ViewBag.SortField, currentSortOrder = ViewBag.SortOrder, currentFilter = ViewBag.CurrentFilter })
                    </th>
                    <th>
                        @Html.ActionLink("Age", "Index", new { sortField = "Age", currentSortField = ViewBag.SortField, currentSortOrder = ViewBag.SortOrder, currentFilter = ViewBag.CurrentFilter })
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.EmpTagNumber)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.EmailAddress)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.FirstName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.LastName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.DepartmentName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.DesignationName)
                        </td>
                        <th>
                            @Html.DisplayFor(modelItem => item.Age)
                        </th>
                        <td>
                            <a href="@Url.Action("Edit", "Employee", new { id = item.Emp_Id })" class="btn btn-primary">Edit</a>
                            @* <a href="@Url.Action("Delete", "Employee", new { id = item.Emp_Id })" class="btn btn-danger">Delete</a>*@
                            <a href="#" class="btn btn-danger delete-btn" data-id="@item.Emp_Id">Delete</a>
                        </td>
                    </tr>

                }
            </tbody>
        </table>
        @{
            var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
            var nextDisabled = !Model.HasNextPage ? "disabled" : "";
            var totalPageNo = Model.TotalPageNo;
            var currentPageNo = Model.PageIndex;
        }

        <a asp-action="Index"
           asp-route-sortOrder="@ViewData["CurrentSort"]"
           asp-route-pageNo="@(Model.PageIndex - 1)"
           asp-route-currentFilter="@ViewData["CurrentFilter"]"
           class="btn btn-default @prevDisabled">
            Previous
        </a>
        <a asp-action="Index"
           asp-route-sortOrder="@ViewData["CurrentSort"]"
           asp-route-pageNo="@(Model.PageIndex + 1)"
           asp-route-currentFilter="@ViewData["CurrentFilter"]"
           class="btn btn-default @nextDisabled">
            Next
        </a>
        <span>
            Page No : @currentPageNo of @totalPageNo
        </span>
    </div>
</div>
<br />



<div class="modal" id="deleteConfirmationModal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Confirm Delete</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Are you sure you want to delete this item?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                <a id="deleteButton" href="#" class="btn btn-danger">Delete</a>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $('.delete-btn').click(function () {
            var id = $(this).data('id');
            $('#deleteButton').attr('href', '@Url.Action("Delete", "Employee")' + '?id=' + id);
            $('#deleteConfirmationModal').modal('show');
        });

        setTimeout(function () {
            $("#message").fadeOut("slow");
        }, 3000);
    });

    function clearFields() {
        document.getElementById("SearchByEmpTag").value = "";
        document.getElementById("SearchByFirstName").value = "";
        document.getElementById("SearchByEmail").value = "";
    }
</script>